Customers.Portal/Areas/BasicInput/Controllers/ManageTasksAnalysisController.cs
using Customers.Abstracts;
using Customers.Abstracts.BasicInput;
using Customers.Model.BasicInput;
using Customers.Portal.Controllers;
using Customers.Portal.Utilities;
using Customers.Resources.GlobalRes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customers.Portal.Areas.BasicInput.Controllers
{
    public class ManageTasksAnalysisController : BaseController
    {
        #region Services

        private readonly ITasksAnalysisService _thisService;
        private readonly CommonService _commonService;

		#endregion

		#region Constructor
        public ManageTasksAnalysisController(ITasksAnalysisService thisService, ILookupService lookupService)
        {
            _thisService = thisService;
            _commonService = new CommonService(lookupService);
		}
		#endregion


        #region Actions

        public ActionResult Index1()
        {
            return View();
        }
        public ActionResult Search(BasicInputSm searchModel)
        {
            var result = _thisService.FindAll(searchModel);
            return PartialView(result);
        }

        public ActionResult Create()
        {
            BasicInputVm Obj = new BasicInputVm();
            return PartialView("~/Areas/BasicInput/Views/ManageTasksAnalysis/Create.cshtml",Obj);
        }
        [HttpPost]
        public JsonResult Create(BasicInputVm viewModel)
        {
                if (viewModel.NameEn == null || viewModel.NameEn == "")
                    viewModel.NameEn = viewModel.NameAr;

                if (_thisService.Save(viewModel))
                {
                    return Json("success," +GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
                }
                else
                    return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

        }
        public ActionResult Edit(int id = 0)
        {
            BasicInputVm obj = _thisService.GetById(id);
            if (obj == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/BasicInput/Views/ManageTasksAnalysis/Create.cshtml", obj);
        }

        public ActionResult Details(int id)
        {
            return PartialView(_thisService.GetById(id));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            BasicInputVm obj = new BasicInputVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/ManageTasksAnalysis/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            if (_thisService.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }
        #endregion
	}
}

Customers.Portal/Areas/BasicInput/Views/ManageTasksAnalysis/Create.cshtml
@model BasicInputVm



@using (Html.BeginForm("Create", "ManageTasksAnalysis", new { area = "BasicInput" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@BasicInputRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.LabelFor(mode => mode.NameAr, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.NameEn, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                </div>

                                <br />
                                <div class="row">
                                    <div class="col-md-1">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
                    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
                    }



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

Customers.Portal/Areas/BasicInput/Views/ManageTasksAnalysis/Delete.cshtml
@model BasicInputVm


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Customers.Portal/Areas/BasicInput/Views/ManageTasksAnalysis/Index1.cshtml
@{
    ViewBag.Title = GlobalRes.TasksAnalysis;
}

<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <input type="button" id="AddNew" onclick="Create()" class="btn yellow " value="@GlobalRes.btnAdd" />
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {

<script src="@Url.Content("~/Areas/BasicInput/Scripts/manageTasksAnalysis.js")"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            manageTasksAnalysis.init();
      
        })

    </script>
}

Customers.Portal/Areas/BasicInput/Views/ManageTasksAnalysis/Search.cshtml
@model IEnumerable<BasicInputVm>

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-striped table-bordered table-hover datatable" width="100%">
                <thead>
                    <tr>
                        <th>@BasicInputRes.Id</th>
                        <th>@BasicInputRes.NameAr</th>
                        <th>@BasicInputRes.NameEn</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.NameAr</td>
                            <td>@item.NameEn</td>

                            <td>
                                <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                    <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                        <li>
                                            <button type="button" class="fa fa-pencil-square-o" id="btnUpdate" onclick="Edit(@item.Id)">@GlobalRes.btnEdit</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <button type="button" class="fa fa-trash" id="btnDelete" onclick="Delete(@item.Id)">@GlobalRes.btnDelete</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <a href="javascript:void(0);"><i class="fa fa-times" aria-hidden="true">@GlobalRes.btnCancel</i></a>
                                        </li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>