Customers.Portal/Areas/BasicInput/Controllers/ManageContractsController.cs
using Customers.Abstracts;
using Customers.Abstracts.Contracts;
using Customers.Model.BasicInput;
using Customers.Model.Contracts;
using Customers.Portal.Controllers;
using Customers.Portal.Utilities;
using Customers.Resources.GlobalRes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customers.Portal.Areas.BasicInput.Controllers
{
    public class ManageContractsController : BaseController
    {
        #region Service

        private readonly IContractsService _thisService;
        private readonly IContractsItemsService _ContractsItemsService;
        private readonly CommonService _commonService;
        #endregion


        #region Constructor
        public ManageContractsController(IContractsService thisService, ILookupService lookupService, IContractsItemsService ContractsItemsService)
        {
            _thisService = thisService;
            _commonService = new CommonService(lookupService);
            _ContractsItemsService = ContractsItemsService;
        }
        #endregion

        #region Actions

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search(BasicInputSm searchModel)
        {
            var result = _thisService.FindAll(searchModel);
            return PartialView(result);
        }

        public ActionResult Create()
        {
            BasicInputVm Obj = new BasicInputVm();

            return PartialView("~/Areas/BasicInput/Views/ManageContracts/Create.cshtml", Obj);
        }


        public ActionResult GetItems()
        {
            ViewBag.ItemsId = _commonService.FindItems();

            return PartialView("_Items");
        }


        [HttpPost]
        public JsonResult Create(BasicInputVm viewModel ,int? ItemsId)
        {

            if (viewModel.NameEn == null || viewModel.NameEn == "")
                viewModel.NameEn = viewModel.NameAr;


            if (viewModel.Id != 0)
            {
                viewModel.Name = viewModel.NameAr;


                
                    if (ItemsId != 0)
                    {
                        ContractsItemsVm C = new ContractsItemsVm();
                        C.ContractsId = viewModel.Id; /*_thisService.FindLast(viewModel).LastOrDefault().Id*/;
                        C.ItemsId = ItemsId;

                        _ContractsItemsService.Save(C);
                    return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);

                }


                else
                    return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);
            }

            else
            {
                if (_thisService.Save(viewModel))
                {
                    if (ItemsId != 0)
                    {
                        ContractsItemsVm C = new ContractsItemsVm();
                        C.ContractsId = _thisService.FindLast(viewModel).LastOrDefault().Id;
                        C.ItemsId = ItemsId;

                        _ContractsItemsService.Save(C);

                    }
                    return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);

                }
                else
                    return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);
            }
        }



        public ActionResult Edit(int id = 0)
        {
            BasicInputVm obj = _thisService.GetById(id);

            if (obj == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/BasicInput/Views/ManageContracts/Create.cshtml", obj);
        }


        public ActionResult Details(int id)
        {
            return PartialView(_thisService.GetById(id));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            BasicInputVm obj = new BasicInputVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/ManageContracts/Delete.cshtml", obj);
        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            if (_thisService.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region Items
        public ActionResult GetItemsList(int? Id)
        {
            ContractsItemsSm searchModel = new ContractsItemsSm();


            var Data = _ContractsItemsService.GetByContractsId(Id);

            return PartialView("_GetItemsList", Data);
        }


        public ActionResult DeleteItems(int id)
        {
            ContractsItemsVm obj = new ContractsItemsVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/ManageContracts/DeleteItems.cshtml", obj);
        }


        public JsonResult DeleteItemsRow(int Id)
        {

            if (_ContractsItemsService.Delete(Id))
            {



                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);

            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Customers.Portal/Areas/BasicInput/Views/ManageContracts/Create.cshtml
@model BasicInputVm


<link href="~/Scripts/select2.css" rel="stylesheet" />


@using (Html.BeginForm("Create", "ManageContracts", new { area = "BasicInput" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog modal-lg" style="width:1000px;">
        <div class="modal-content" style="width:1000px;">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title">@BasicInputRes.Details</h4>
            </div>
            <div class="modal-body" style="width:1000px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="form-group row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.LabelFor(mode => mode.NameAr, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">


                                        <input type="text" class="form-control" id="NameAr" name="NameAr" value="@Model.NameAr">
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.NameEn, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="NameEn" name="NameEn" value="@Model.NameEn">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>


                                <br />
                               
                               
                               
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title"> البنود</h4>
                                </div>

                                <br />
                                @Html.Action("GetItems")
                           
                               
                                <br />
                                <br />
                                <br />
                                <div class="row">
                                    <div class="col-md-2">

                                    </div>
                                    <div class="col-md-8">
                                        @Html.Action("GetItemsList", new { Id = Model.Id })


                                    </div>
                                </div>
                                

                                @*@if (Model.Id != 0)
                                {
                                    <div class="row">
                                        <div class="col-md-2"></div>
                                        <div class="col-md-10">
                                            <br />
                                            @Html.Action("CommunicationOfficer", new { Id = Model.Id })


                                        </div>
                                    </div>
                                }
                                <br />*@
                                <div class="row">
                                    <div class="col-md-5">

                                    </div>
                                    <div class="col-md-5">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>

                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
                    }



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

<script src="~/Scripts/select2.min.js"></script>
<script>
        $(document).ready(function () {
            $('.select2').select2();
            // $('.select5').select2();
        });
</script>

Customers.Portal/Areas/BasicInput/Views/ManageContracts/Delete.cshtml
@model BasicInputVm


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Customers.Portal/Areas/BasicInput/Views/ManageContracts/DeleteItems.cshtml
@model Customers.Model.Contracts.ContractsItemsVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteItemsRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

Customers.Portal/Areas/BasicInput/Views/ManageContracts/Index1.cshtml
@{
    ViewBag.Title = GlobalRes.Contracts;
}

<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <input type="button" id="AddNew" onclick="Create()" class="btn yellow " value="@GlobalRes.btnAdd" />
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {

<script src="@Url.Content("~/Areas/BasicInput/Scripts/ManageContracts.js")"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            ManageContracts.init();
      
        })

    </script>
}

Customers.Portal/Areas/BasicInput/Views/ManageContracts/Search.cshtml
@model IEnumerable<BasicInputVm>

<div class="">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-striped table-bordered table-hover datatable" width="100%">
                <thead>
                    <tr>
                        <th>@BasicInputRes.Id</th>
                        <th>@BasicInputRes.NameAr</th>
                        <th>@BasicInputRes.NameEn</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.NameAr</td>
                            <td>@item.NameEn</td>

                            <td>
                                <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                    <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                        <li>
                                            <button type="button" class="fa fa-pencil-square-o" id="btnUpdate" onclick="Edit(@item.Id)">@GlobalRes.btnEdit</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <button type="button" class="fa fa-trash" id="btnDelete" onclick="Delete(@item.Id)">@GlobalRes.btnDelete</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <a href="javascript:void(0);"><i class="fa fa-times" aria-hidden="true">@GlobalRes.btnCancel</i></a>
                                        </li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
</div>

        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>

Customers.Portal/Areas/BasicInput/Views/ManageContracts/_GetItemsList.cshtml
@model IEnumerable<Customers.Model.Contracts.ContractsItemsVm>

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-striped table-bordered table-hover datatable" width="100%">
                <thead>
                    <tr>

                        <th>الكود</th>
                        <th>اسم البند</th>





                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>

                            <td>@item.Id</td>
                            <td>@item.ItemsName</td>






                            <td>
                                <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                    <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                        <li>
                                            @*<button type="button" class="fa fa-pencil-square-o" id="btnUpdate" onclick="EditComm(@item.Id,'@item.Name','@item.JobeName','@item.PhoneNumber','@item.Email')"></button>*@
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <button type="button" class="fa fa-trash" id="btnDelete" onclick="DeleteItems(@item.Id)"></button>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <a href="javascript:void(0);"><i class="fa fa-times" aria-hidden="true"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>

        </div>
    </div>

<script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


</script>

Customers.Portal/Areas/BasicInput/Views/ManageContracts/_Items.cshtml
@model Customers.Model.Contracts.ContractsItemsVm


<div class="row">

    <div class="col-md-2">
        @Html.LabelFor(mode => mode.ItemsId, htmlAttributes: new { @class = "control-label" })
    </div>
    <div class="col-md-4">

        @Html.EditorFor(model => model.ItemsId, new { htmlAttributes = new { @class = "form-control input-circle" } })
    </div>


</div>